// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  handbookSidebar: [
    'index',
    {
      type: 'category',
      label: 'Вступление',
      link: {
        type: 'doc',
        id: 'intro/vvedenie',
      },
      items: [{type: 'autogenerated', dirName: '01_intro'}],
    },
    {
      type: 'category',
      label: 'Модуль 0. Базовая карта проекта',
      link: {
        type: 'doc',
        id: 'module_0_basics/module_0_overview',
      },
      items: [{type: 'autogenerated', dirName: '02_module_0_basics'}],
    },
    {
      type: 'category',
      label: 'Модуль 1. BIM',
      link: {
        type: 'doc',
        id: 'module_1_bim/module_1_overview',
      },
      items: [{type: 'autogenerated', dirName: '03_module_1_bim'}],
    },
    {
      type: 'category',
      label: 'Модуль 2. BIM-координатор',
      link: {
        type: 'doc',
        id: 'module_2_bim_coordinator/module_2_overview',
      },
      items: [{type: 'autogenerated', dirName: '04_module_2_bim_coordinator'}],
    },
    {
      type: 'category',
      label: 'Модуль 3. Revit-модель',
      link: {
        type: 'doc',
        id: 'module_3_revit/module_3_overview',
      },
      items: [{type: 'autogenerated', dirName: '05_module_3_revit'}],
    },
    {
      type: 'category',
      label: 'Модуль 4. IFC',
      link: {
        type: 'doc',
        id: 'module_4_ifc/module_4_overview',
      },
      items: [{type: 'autogenerated', dirName: '06_module_4_ifc'}],
    },
    {
      type: 'category',
      label: 'Модуль 5. Документы и требования',
      link: {
        type: 'doc',
        id: 'module_5_requirements/module_5_overview',
      },
      items: [{type: 'autogenerated', dirName: '07_module_5_requirements'}],
    },
    {
      type: 'category',
      label: 'Модуль 6. АГР',
      link: {
        type: 'doc',
        id: 'module_6_agr/module_6_overview',
      },
      items: [{type: 'autogenerated', dirName: '08_module_6_agr'}],
    },
    {
      type: 'category',
      label: 'Модуль 7. Экспертиза',
      link: {
        type: 'doc',
        id: 'module_7_expertise/module_7_overview',
      },
      items: [{type: 'autogenerated', dirName: '09_module_7_expertise'}],
    },
    {
      type: 'category',
      label: 'Модуль 8. Зоны, площади и ТЭП',
      link: {
        type: 'doc',
        id: 'module_8_areas_teps/module_8_overview',
      },
      items: [{type: 'autogenerated', dirName: '10_module_8_areas_teps'}],
    },
    {
      type: 'category',
      label: 'Модуль 9. Параметры и классификация',
      link: {
        type: 'doc',
        id: 'module_9_parameters/module_9_overview',
      },
      items: [{type: 'autogenerated', dirName: '11_module_9_parameters'}],
    },
    {
      type: 'category',
      label: 'Модуль 10. QC',
      link: {
        type: 'doc',
        id: 'module_10_qc/module_10_overview',
      },
      items: [{type: 'autogenerated', dirName: '12_module_10_qc'}],
    },
    {
      type: 'category',
      label: 'Модуль 11. Работа на проекте',
      link: {
        type: 'doc',
        id: 'module_11_project_work/module_11_overview',
      },
      items: [{type: 'autogenerated', dirName: '13_module_11_project_work'}],
    },
    {
      type: 'category',
      label: 'Модуль 12. Ошибки и кейсы',
      link: {
        type: 'doc',
        id: 'module_12_cases/module_12_overview',
      },
      items: [{type: 'autogenerated', dirName: '14_module_12_cases'}],
    },
    {
      type: 'category',
      label: 'Модуль 13. Рост координатора',
      link: {
        type: 'doc',
        id: 'module_13_growth/module_13_overview',
      },
      items: [{type: 'autogenerated', dirName: '15_module_13_growth'}],
    },
    {
      type: 'category',
      label: 'Заключение',
      link: {
        type: 'doc',
        id: 'conclusion/zaklyuchenie',
      },
      items: [{type: 'autogenerated', dirName: '16_conclusion'}],
    },
    {
      type: 'category',
      label: 'Приложения',
      link: {
        type: 'doc',
        id: 'appendices/APPENDICES_OVERVIEW',
      },
      items: [{type: 'autogenerated', dirName: '90_appendices'}],
    },
  ],
};

export default sidebars;
