// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  handbookSidebar: [
    'index',
    {
      type: 'category',
      label: 'Вступление',
      link: {
        type: 'generated-index',
        title: 'Вступление',
        description: 'Как читать handbook и почему модель нужно воспринимать как источник данных.',
      },
      items: [{type: 'autogenerated', dirName: '01_intro'}],
    },
    {
      type: 'category',
      label: 'Модуль 0. Базовая карта проекта',
      link: {
        type: 'generated-index',
        title: 'Модуль 0',
        description: 'Среда проектирования, участники, стадии, площади, АГР и экспертиза.',
      },
      items: [{type: 'autogenerated', dirName: '02_module_0_basics'}],
    },
    {
      type: 'category',
      label: 'Модуль 1. BIM',
      link: {
        type: 'generated-index',
        title: 'Модуль 1',
        description: 'BIM простыми словами: процесс, модель и типовые ошибки мышления.',
      },
      items: [{type: 'autogenerated', dirName: '03_module_1_bim'}],
    },
    {
      type: 'category',
      label: 'Модуль 2. BIM-координатор',
      link: {
        type: 'generated-index',
        title: 'Модуль 2',
        description: 'Роль координатора, ежедневная работа, навыки и типовые ошибки.',
      },
      items: [{type: 'autogenerated', dirName: '04_module_2_bim_coordinator'}],
    },
    {
      type: 'category',
      label: 'Модуль 3. Revit-модель',
      link: {
        type: 'generated-index',
        title: 'Модуль 3',
        description: 'Авторская модель, базовая структура и качество модели в логике проекта.',
      },
      items: [{type: 'autogenerated', dirName: '05_module_3_revit'}],
    },
    {
      type: 'category',
      label: 'Модуль 4. IFC',
      link: {
        type: 'generated-index',
        title: 'Модуль 4',
        description: 'IFC как слой обмена, проверки и автоматизации.',
      },
      items: [{type: 'autogenerated', dirName: '06_module_4_ifc'}],
    },
    {
      type: 'category',
      label: 'Модуль 5. Документы и требования',
      link: {
        type: 'generated-index',
        title: 'Модуль 5',
        description: 'Как читать документы, выделять требования и переводить их в рабочие таблицы.',
      },
      items: [{type: 'autogenerated', dirName: '07_module_5_requirements'}],
    },
    {
      type: 'category',
      label: 'Модуль 6. АГР',
      link: {
        type: 'generated-index',
        title: 'Модуль 6',
        description: 'Требования АГР к цифровой модели, ТЭП и сопроводительным материалам.',
      },
      items: [{type: 'autogenerated', dirName: '08_module_6_agr'}],
    },
    {
      type: 'category',
      label: 'Модуль 7. Экспертиза',
      link: {
        type: 'generated-index',
        title: 'Модуль 7',
        description: 'Логика экспертизы, отличия от АГР и машиночитаемые проверки.',
      },
      items: [{type: 'autogenerated', dirName: '09_module_7_expertise'}],
    },
    {
      type: 'category',
      label: 'Модуль 8. Зоны, площади и ТЭП',
      link: {
        type: 'generated-index',
        title: 'Модуль 8',
        description: 'Центральная расчетная связка модели: помещения, зоны, IfcSpace и показатели.',
      },
      items: [{type: 'autogenerated', dirName: '10_module_8_areas_teps'}],
    },
    {
      type: 'category',
      label: 'Модуль 9. Параметры и классификация',
      link: {
        type: 'generated-index',
        title: 'Модуль 9',
        description: 'Атрибуты, источники значений, МССК и карта параметров.',
      },
      items: [{type: 'autogenerated', dirName: '11_module_9_parameters'}],
    },
    {
      type: 'category',
      label: 'Модуль 10. QC',
      link: {
        type: 'generated-index',
        title: 'Модуль 10',
        description: 'Проверки качества модели, негеометрические ошибки и готовность к выдаче.',
      },
      items: [{type: 'autogenerated', dirName: '12_module_10_qc'}],
    },
    {
      type: 'category',
      label: 'Модуль 11. Работа на проекте',
      link: {
        type: 'generated-index',
        title: 'Модуль 11',
        description: 'Аудит, замечания, коммуникация и ведение BIM-процесса.',
      },
      items: [{type: 'autogenerated', dirName: '13_module_11_project_work'}],
    },
    {
      type: 'category',
      label: 'Модуль 12. Ошибки и кейсы',
      link: {
        type: 'generated-index',
        title: 'Модуль 12',
        description: 'Спорные случаи, типовые провалы и системное мышление координатора.',
      },
      items: [{type: 'autogenerated', dirName: '14_module_12_cases'}],
    },
    {
      type: 'category',
      label: 'Модуль 13. Рост координатора',
      link: {
        type: 'generated-index',
        title: 'Модуль 13',
        description: 'Как развиваться дальше после освоения базового маршрута.',
      },
      items: [{type: 'autogenerated', dirName: '15_module_13_growth'}],
    },
    {
      type: 'category',
      label: 'Заключение',
      link: {
        type: 'generated-index',
        title: 'Заключение',
        description: 'Финальная рамка учебника и маршрут возвращения к нему в работе.',
      },
      items: [{type: 'autogenerated', dirName: '16_conclusion'}],
    },
    {
      type: 'category',
      label: 'Приложения',
      link: {
        type: 'doc',
        id: 'appendices/APPENDICES_OVERVIEW',
      },
      items: [{type: 'autogenerated', dirName: '90_appendices'}],
    },
  ],
};

export default sidebars;




